
export const metadata = {
  title: 'Consultor IA',
  description: 'Generated by Next.js',
}

import React from 'react'
import '../app/styles/globals.css';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body>{children}</body>
    </html>
  )
}
